###
GET {{controller}}/platform/kubefox/deployment

###
POST {{controller}}/platform/kubefox/deployment
Content-Type: application/json

<@ ./resources/deploy-demo-main.json
###
POST {{controller}}/platform/kubefox/deployment
Content-Type: application/json

<@ ./resources/deploy-demo-v0.1.0.json
###
POST {{controller}}/platform/kubefox/deployment
Content-Type: application/json

<@ ./resources/deploy-demo-v0.1.1.json

###
GET {{controller}}/platform/kubefox/deployment/demo/branch/main
###
GET {{controller}}/platform/kubefox/deployment/demo/tag/v0.1.0
###
GET {{controller}}/platform/kubefox/deployment/demo/tag/v0.1.1

###
DELETE {{controller}}/platform/kubefox/deployment/demo/branch/main
###
DELETE {{controller}}/platform/kubefox/deployment/demo/tag/v0.1.0
###
DELETE {{controller}}/platform/kubefox/deployment/demo/tag/v0.1.1
