# Copyright 2023 XigXog
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

FROM alpine
ARG COMPONENT
COPY ./bin/${COMPONENT} /component
ENTRYPOINT [ "/component" ]
