@imagePullSecret = {{$processEnv GH_IMAGE_PULL_SECRET}}

###
GET {{controller}}/system

###
POST {{controller}}/system/demo
Content-Type: application/json

<@ ./resources/system-hello-v0.1.0.json

###
POST {{controller}}/system/demo
Content-Type: application/json

<@ ./resources/system-demo-v0.1.1.json

###
GET {{controller}}/system/demo

###
GET {{controller}}/system/demo/branch/main
###
PUT {{controller}}/system/demo/branch/main

bbbbbbb
###
POST {{controller}}/system/hello-world/tag/v0.1.0

aaaaaaa
###
POST {{controller}}/system/demo/tag/v0.1.1

bbbbbbb