apiVersion: kubefox.xigxog.io/v1alpha1
kind: Environment
metadata:
  name: qa
spec:
  releasePolicy:
    versionRequired: false
    dataSnapshotRequired: false
data:
  vars:
    who: World
    subPath: qa
---
apiVersion: kubefox.xigxog.io/v1alpha1
kind: VirtualEnvironment
metadata:
  name: qa
spec:
  environment: qa
