apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world-native
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world-native
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: localhost/hello-world-frontend:main
          args:
            - -addr=0.0.0.0:3333
          envFrom:
            - configMapRef:
                name: env
          ports:
            - containerPort: 3333
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-frontend
spec:
  selector:
    app.kubernetes.io/name: hello-world-native
    app.kubernetes.io/component: frontend
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3333
      protocol: TCP
