apiVersion: apps/v1
kind: StatefulSet
{{ include "metadata" . }}
spec:
  serviceName: {{ componentFullName }}
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "selectors" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
      annotations:
        kubefox.xigxog.io/config-hash: {{ file "nats/nats.conf" | sha256sum }}
        {{- include "annotations" . | nindent 8 }}
    spec:
      {{- include "podSpec" . | nindent 6 }}
      shareProcessNamespace: true
      initContainers:
        - {{- include "bootstrap" . | nindent 10 }}
      containers:
        - name: {{ .Component.Name }}
          image: {{ .Component.Image | quote }}
          imagePullPolicy: {{ .Component.ImagePullPolicy | default "IfNotPresent" }}
          {{- include "securityContext" . | nindent 10 }}
          {{- include "resources" . | nindent 10 }}
          {{- include "probes" . | nindent 10 }}
          command:
            - "nats-server"
            - "--config"
            - "/etc/nats/nats.conf"
          env:
          {{- include "env" . | nindent 12 }}
            - name: KUBEFOX_COMPONENT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: {{ name }}-env
          ports:
            - name: client
              containerPort: 4222
            - name: monitor
              containerPort: 8222
          volumeMounts:
            - name: config
              mountPath: /etc/nats
            - name: pid
              mountPath: /var/run/nats
            - name: root-ca
              mountPath: {{ homePath }}/ca.crt
              subPath: ca.crt
            - name: kubefox
              mountPath: {{ homePath }}
          lifecycle:
            preStop:
              exec:
                # Send the lame duck shutdown signal to trigger a graceful
                # shutdown nats-server will ignore the TERM signal it receives
                # after this.
                command:
                  - "nats-server"
                  - "-sl=ldm=/var/run/nats/nats.pid"
      volumes:
        - name: config
          configMap:
            name: {{ componentFullName }}-config
        - name: pid
          emptyDir: {}
        - name: root-ca
          configMap:
            name: {{ .Instance.Name }}-root-ca
        - name: kubefox
          emptyDir: {}
